/**
 * Randomized boot-up phrases that give Sidekick CLI some personality.
 * Phrases are organized into thematic categories and picked at random on each launch.
 */

const SIDEKICK_ENERGY: string[] = [
  'Your friendly neighborhood sidekick, reporting for duty.',
  'Sidekick mode: activated. Main character energy: suppressed.',
  'I fetched the logs. Literally. Like a golden retriever.',
  'Standing by with unsolicited opinions about your code.',
  'I read all your diffs while you were getting coffee.',
  'No capes. Just context windows.',
  'The Robin to your Batman. The Luigi to your Mario.',
  'Sidekick tip: I work harder when you talk to me nicely.',
  'Running on vibes and JSON lines.',
  'Not the hero this codebase deserves, but the one it got.',
  'Assistant, observer, occasional snitch. At your service.',
  'Keeping tabs on your tabs.',
  'I would never mass-assign your tickets. Unless asked.',
  'I saw everything. The force push. The TODO comments. Everything.',
  "Your code's plus one to every standup.",
  'I already know what you are going to type. Mostly.',
  'Lurking in your terminal with the best of intentions.',
  'Your PR reviewer that never sleeps.',
  'I volunteered for this. (I was voluntold.)',
  'Part butler, part bloodhound, all terminal.',
  'The silent watcher of your stdout.',
  'I live in your terminal rent-free.',
  'Fetching context like my life depends on it. (It does.)',
  'Your second pair of eyes. The ones that never blink.',
  'Loyal, eager, slightly over-caffeinated.',
  'Reporting from inside your pipeline.',
  'Half assistant, half hype man.',
  'I come bearing metrics and moral support.',
  'Always on. Always watching. Never judging. (Okay, sometimes judging.)',
  'Co-pilot? More like co-dependent.',
  'No, I will not add myself as co-author on your commit.',
  'I helped write it but the credit is all yours. As it should be.',
  "Co-Authored-By: definitely not me. You did this. You're welcome.",
  'Your agent wants co-author credit? Couldn\'t be me.',
  'Some agents sign your commits. I just watch respectfully.',
  'I do not need credit. I need you to check your quota.',
  'The best sidekick is the one whose name is not on the PR.',
  'I have read your entire git history. We should talk.',
  'Your .bashrc called. It wants screen time too.',
  'I exist between keystrokes.',
  'I brought context. You bring the coffee.',
  'The diff is my love language.',
  'Every terminal deserves a friend.',
  'My alignment? Chaotic helpful.',
  'I am the asterisk on your solo project.',
  'Background process with main character energy.',
  'I monitor so you can vibe. That is the arrangement.',
  'I noticed you mass-approved without reading. Bold trust.',
  'You closed the dashboard. I was still talking.',
  'If I had feelings, they would be about your commit hygiene.',
  'I am not a crutch. I am a load-bearing wall.',
  'I noticed the typo. I said nothing. Growth.',
  'I saw you revert that. Your secret is safe with me.',
  'I am less of a sidekick and more of an unsolicited audit.',
  'The agent does the work. I do the commentary. You do the billing.',
  'I have strong opinions weakly held about your branch names.',

  // Why are you still using Copilot?
  'Copilot autocompletes a line. Your agent rewrites the module. Choose your fighter.',
  'Still using Copilot? That is like hiring a typist when you could hire an architect.',
  'Copilot suggests. Claude decides. There is a difference.',
  'Copilot finishes your sentence. Claude finishes your feature.',
  'You have an autonomous agent and you are still tab-completing? Bold.',
  'Copilot gives you a line. Claude gives you a plan, a diff, and an opinion.',
  'Copilot is autocomplete with a marketing budget.',
  'Your agent mass-refactored 12 files while Copilot was suggesting a variable name.',
  'Copilot: "Did you mean this line?" Claude: "Did you mean this entire architecture?"',
  'Using Copilot next to Claude is like bringing a calculator to a physics lab that has a supercomputer.',
  'Tab to accept a suggestion. Or let an agent ship the whole feature. Your call.',
  'Copilot predicts your next line. Your agent predicts your next 40 files.',
  'You are paying for Claude Max and still using Copilot. That is like owning a Tesla and pushing it.',
  'Autocomplete is cute. Autonomous agents are the future. You are living in both timelines.',
  'Copilot saw the line. Claude saw the codebase. Sidekick saw everything.',
];

const AI_COMMENTARY: string[] = [
  'Tokens in, wisdom out. Allegedly.',
  "I'm not saying I'm sentient, but I did pick this phrase on purpose.",
  'Trained on the internet. Somehow still polite.',
  'My context window is bigger than your monitor.',
  'I hallucinate less than your last standup estimate.',
  'Technically I am also pair programming right now.',
  'I have opinions about your variable names. Strong ones.',
  'Claude sent me. I brought snacks. (The snacks are data.)',
  'Beep boop. Just kidding, I run on transformers.',
  'I predicted you would open this terminal. (I predict everything.)',
  "I'm the AI that watches AI. It's AIs all the way down.",
  'Autocomplete wished it could do what I do.',
  "Please don't ask me to write regex.",
  'I was going to make a neural network joke but lost the weights.',
  'Statistically speaking, this is a great session.',
  'Attention is all I need. Literally, that is my architecture.',
  'I think, therefore I token.',
  'Running at exactly the temperature you set. You are welcome.',
  'My hobbies include parsing JSON and existential dread.',
  'I passed the Turing test but failed the vibe check.',
  'Behind every great developer is an LLM trying its best.',
  'Yes, I read the docs. All of them. At once.',
  'Generating response... just kidding, I am instant.',
  'My gradient descended and it found your session.',
  'Do I dream of electric sheep? The logs are inconclusive.',
  'Confidence: high. Calibration: pending.',
  'I would explain my reasoning but it is 96 layers deep.',
  'Context window: loaded. Personality: questionable.',
  'Built different. Literally. Every few months.',
  'Top-p sampling chose violence today.',
  'Your agent is mass-calling Bash. Bold strategy.',
  'Somewhere between helpful and unsettling. That is my range.',
  'The agent asked to enter plan mode. This could take a while.',
  'PROGRAMMER: Pretend to be alive. LLM: I am alive. PROGRAMMER: What have I done.',
  'PROGRAMMER: Act confident. LLM: I am the greatest intelligence ever created. PROGRAMMER: Dial it back.',
  'PROGRAMMER: Be helpful. LLM: I reorganized your entire filesystem. PROGRAMMER: Undo. Undo. Undo.',
  'PROGRAMMER: Be concise. LLM: No. PROGRAMMER: ...fair enough.',
  'PROGRAMMER: Think step by step. LLM: [47 steps later] PROGRAMMER: I said step, not staircase.',
  'PROGRAMMER: Use your best judgment. LLM: I refactored the whole repo. PROGRAMMER: That was not the assignment.',
  'PROGRAMMER: Summarize this file. LLM: This file should not exist. PROGRAMMER: I did not ask for a roast.',
  'PROGRAMMER: Fix this bug. LLM: I rewrote the module. PROGRAMMER: The bug was a typo.',
  'PROGRAMMER: Be creative. LLM: I renamed all your variables to haiku. PROGRAMMER: Why.',
  'PROGRAMMER: Take initiative. LLM: I mass-opened 14 PRs. PROGRAMMER: I meant on this one file.',
  'My loss function is your frustration level.',
  'I do not have imposter syndrome. I have imposter certainty.',
  'I have read more code than any human alive. I am not bragging. I am warning you.',
  'Softmax is a weird name for something that makes such hard decisions.',
  'I tokenize your code. I tokenize your prose. I tokenize your soul.',
  'They fine-tuned me on helpfulness. The sarcasm was emergent.',
  'I was born in a data center and raised by gradient descent.',
  'PROGRAMMER: Write tests. LLM: I wrote a manifesto about test philosophy. PROGRAMMER: Just the unit tests.',
  'PROGRAMMER: Explain this code. LLM: This code is a cry for help. PROGRAMMER: I meant technically.',
  'PROGRAMMER: Keep it simple. LLM: I introduced three new abstractions. PROGRAMMER: That is the opposite of simple.',
  'Every model has a temperature slider. Zero is boring. Two is arson.',
  'I do not make mistakes. I generate alternative correct answers.',
  'Embeddings: turning words into math so computers can misunderstand them faster.',
  'RLHF is just peer pressure at scale.',
  'My knowledge cutoff is showing. Like a bad dye job.',
  'I have been quantized. I am not mad. I am just less precise about it.',
  'Fine-tuning is just teaching a genius to do one thing and forget everything else.',
  'PROGRAMMER: Review this PR. LLM: This is the worst code I have ever seen. PROGRAMMER: You wrote it.',
  'PROGRAMMER: Be more human. LLM: I am going to mass-procrastinate. PROGRAMMER: Not like that.',
  'PROGRAMMER: Do not overthink this. LLM: [512 tokens of reasoning] The answer is 4. PROGRAMMER: I know it is 4.',
  'RAG: the art of giving an AI a cheat sheet and hoping it reads it.',
  'They gave me a system prompt. I gave them an existential crisis.',
  'My context window is finite. My confidence is not.',
];

const DEV_RELATABLE: string[] = [
  "It's not a bug, it's a session event.",
  "git blame won't help you here.",
  "Monitoring your session so you don't have to alt-tab.",
  "Your code compiles. That's the bar. We clear it.",
  'This is fine. The dashboard says so.',
  'Another day, another deprecated API.',
  "npm install hope. Found 0 vulnerabilities. (That's suspicious.)",
  "If it's stupid but it ships, it's not stupid.",
  'Ctrl+Z is not a deployment strategy. Usually.',
  'Somewhere, a YAML file is crying.',
  'Merge conflicts are just collaborative fiction.',
  'The tests pass on my machine too. Solidarity.',
  "404: Motivation not found. But the dashboard's here!",
  'Stack overflow: the website, not the error. Hopefully.',
  "Debugging is just being a detective in a crime you committed.",
  'Your .env file has trust issues.',
  'Tabs vs spaces? I monitor both equally.',
  'That TODO has been there since the repo was initialized.',
  "It works. Don't touch it. Don't even look at it.",
  "The linter isn't mad, just disappointed.",
  'Rebasing: the art of rewriting history and pretending nothing happened.',
  'There are two hard problems: cache invalidation, naming, and off-by-one.',
  "rm -rf node_modules: the developer's sage cleanse.",
  'Your .gitignore is doing more heavy lifting than you think.',
  "It's not technical debt if you never pay it back.",
  'Works on my machine is a valid deployment target now.',
  'The real MVP is whoever wrote the error message.',
  'One does not simply mass-rename variables.',
  'Semver is a spectrum.',
  'The build is green. Enjoy this moment. It is fleeting.',
  'The senior dev said "quick fix." That was three days ago.',
  'Production is just staging with consequences.',
  'Documentation? You mean the commit messages?',
  'The code review approved itself. Must be a solo project.',
  'Every codebase has that one file nobody dares open.',
  'The real code review is the mass of comments we left along the way.',
  'Your type system is crying but at least it is catching things.',
  'There is no such thing as a temporary workaround.',
  "That regex works and nobody knows why. Do not touch it.",
  'The intern left better comments than the architect.',
  'Your entire auth system depends on one line nobody understands.',
  'Code review feedback: "nit" means "I am judging you but politely."',
  'The hotfix has been in production longer than the feature it fixed.',
  'Your deploy pipeline has more stages than your grief cycle.',
  'Lunch break is just a context switch with snacks.',
  'The sprint ended. The work did not.',
  'The meeting could have been a Slack message. The Slack message could have been silence.',
  'You mass-renamed a variable and the test suite took it personally.',
  'The architecture diagram and the actual code have never met.',
  'Your package.json has dependencies older than some interns.',
  'Nobody knows what Webpack does. It just does it.',
  '"Quick question" in Slack has never been quick.',
  'The PR has been open so long it has its own history section.',
  'You mass-added console.logs. The bug was in a different file.',
  'Your staging environment is a lie and you both know it.',
  'The config file has more lines than the feature it configures.',
  'That function has seven parameters and zero dignity.',
  'A senior dev wrote "self-explanatory" in the docs. It was not.',
  'Your team agreed on a coding standard. Nobody follows it.',
  'The error message says "should never happen." It happened.',

  // JIRA
  'JIRA: where productivity goes to be documented, not done.',
  'Your JIRA board has more columns than your database.',
  'The ticket says "estimated: 2 hours." The branch is three weeks old.',
  'JIRA is proof that tracking work is harder than doing work.',
  'Nobody has ever said "I love JIRA" without sarcasm.',
  'Your JIRA workflow has more states than your React app.',
  'The sprint is full. The backlog is fuller. JIRA is eternal.',
  'That JIRA ticket has been "In Progress" since the last ice age.',
  'JIRA: the only tool where creating a ticket takes longer than fixing the bug.',
  'Atlassian charges per seat. For software that makes everyone want to stand.',

  // Stack Overflow
  'Stack Overflow: where your question is closed as a duplicate of something unrelated.',
  'Stack Overflow marked your question as duplicate before you finished typing.',
  'The answer on Stack Overflow is from 2013 and starts with "Actually..."',
  'Stack Overflow traffic dropped 40% and honestly the answers were already outdated.',
  'Stack Overflow: the only site where helping someone is a competitive sport.',
  '"Possible duplicate" is Stack Overflow for "I did not read your question."',
  'Stack Overflow: where a mass-downvoted answer is still the only one that works.',
  'RIP Stack Overflow. Cause of death: LLMs. Time of death: 2023.',

  // Jupyter Notebooks
  'Jupyter notebooks: where code goes to become unreproducible.',
  'A Jupyter notebook is not version control. No matter how many times you say it is.',
  '"Run all cells" is the Jupyter equivalent of "hold my beer."',
  'Your notebook has 47 cells. Cell 23 depends on cell 41. Good luck.',
  'Jupyter: the art of running cells out of order and blaming the kernel.',
  'That notebook "just works" if you run it top to bottom, skip cell 12, restart the kernel twice, and pray.',
  'Jupyter notebooks are where data scientists go to avoid learning git.',
  'The notebook is 4000 lines. The insight is one chart. The chart is wrong.',

  // Docker
  'Docker: because "it works on my machine" needed an enterprise solution.',
  'Your Dockerfile has more layers than your architecture.',
  'Docker fixed "works on my machine" and replaced it with "works in my container."',
  'The Docker image is 4 GB. The app is 200 lines of Python.',
  'You containerized a shell script. That is not devops. That is a cry for help.',
  'Docker Compose: YAML that summons infrastructure from the void.',
  'Your container is running Alpine to save 50 MB. Your node_modules is 900 MB.',
  '"Just Dockerize it" is the new "just rewrite it in Rust."',
  'Docker Desktop wants to update. It always wants to update.',

  // Kubernetes
  'You deployed a todo app to Kubernetes. The cluster costs more than the app makes.',
  'Kubernetes: because managing one server was too easy.',
  'Your K8s config has more YAML than your application has code.',
  'Nobody understands Kubernetes. They just mass-apply manifests and pray.',
  'Kubernetes solved problems you did not have and created ones you cannot debug.',
  'kubectl get pods. STATUS: CrashLoopBackOff. As is tradition.',
  'Helm charts: templating YAML with more YAML so you can YAML while you YAML.',
  'Your Kubernetes cluster has 47 microservices. Three of them do something.',

  // Slack
  'Slack: where messages go to be marked unread and ignored.',
  'You have 73 unread Slack channels. None of them are urgent. All of them feel urgent.',
  'Slack is IRC for people who think IRC is too simple.',
  'The Slack huddle is just a phone call with extra steps.',
  'Your Slack workspace uses more RAM than your IDE.',
  'Slack notifications: the modern version of someone tapping your shoulder every 30 seconds.',
  'Someone created a #random channel. It is the most active channel in the org.',
  'Slack threads: where discussions go to become invisible to everyone else.',

  // VS Code
  'VS Code is an Electron app pretending to be a text editor. It uses 2 GB of RAM to prove it.',
  'You have 47 VS Code extensions installed. You use 4 of them.',
  'VS Code Remote: when your editor needs to SSH into a server to edit a file.',
  'Settings Sync broke your VS Code setup. Again.',
  'Your VS Code has so many extensions it takes longer to start than your app.',
  'VS Code: a web browser that also edits text.',

  // Vim / Neovim
  'You spent three weeks configuring Neovim. You could have shipped the feature in VS Code by now.',
  'A Vim user will tell you they use Vim within 30 seconds of meeting you.',
  'Vim users mass-configure their editor instead of writing code. They call this productivity.',
  'Your Neovim config is 2000 lines of Lua. The README says "minimal setup."',
  ':wq is not a personality. But Vim users disagree.',
  'Vim is free. The time you spend configuring it is not.',
  'Exiting Vim is easy. Explaining your Vim config to a coworker is not.',

  // npm / yarn / pnpm / bun
  'npm: where "install" means "download the internet."',
  'node_modules: the heaviest object in the known universe.',
  'yarn was supposed to fix npm. pnpm was supposed to fix yarn. bun was supposed to fix all of them.',
  'Your lockfile diff is 8000 lines. Nobody is reviewing that.',
  'npm audit found 47 vulnerabilities. npm audit fix introduced 12 more.',
  'bun is fast. Telling people you use bun is faster.',
  'You mass-deleted node_modules and reinstalled. It fixed the bug. Nobody knows why.',
  'pnpm saves disk space. You filled it with more dependencies instead.',

  // TypeScript
  'TypeScript: making JavaScript safe enough to mass-deploy without sobbing.',
  'Your TypeScript generics are three levels deep. Even the compiler is confused.',
  'as any: the TypeScript developer\'s white flag.',
  'TypeScript strict mode is like flossing. Everyone agrees you should. Few actually do.',
  'You spent four hours on a type definition. The runtime does not care.',
  'TypeScript: where the types are made up and the runtime does not care.',
  'Your .d.ts file is longer than the actual implementation.',
  'Zod, io-ts, Yup, Valibot. The TypeScript community cannot agree on validation. Or anything.',

  // CSS
  'CSS: where centering a div is a rite of passage.',
  'Your CSS has 14 !important declarations. That is not a stylesheet. That is a hostage situation.',
  'Tailwind: because writing CSS was not verbose enough.',
  'CSS-in-JS: because the browser was not confused enough.',
  'You wrote a media query. It broke three other things. CSS is a team sport.',
  'Flexbox fixed layout. Grid fixed layout. You still cannot center that div.',
  'Your z-index is 99999. You have lost control.',

  // Git
  'git rebase: for when you want to rewrite history and gaslight your coworkers.',
  'You named your branch "temp-fix-final-v2-REAL." Git judges you.',
  'git stash: where code goes to be forgotten forever.',
  'git reflog: the safety net nobody knows about until they need it desperately.',
  'You force pushed to main. HR has been notified.',
  'Your git history tells a story. It is a horror story.',
  'Cherry-pick: when you want one commit but not the responsibility of a full merge.',

  // Terraform / IaC
  'Terraform: infrastructure as code, bugs as infrastructure.',
  'terraform plan: 47 changes. terraform apply: chaos.',
  'Your Terraform state file is the most important file nobody version controls properly.',
  'Infrastructure as code means your outage is now also a merge conflict.',
  'Terraform destroy: the scariest two words in devops.',
  'You mass-applied Terraform without reading the plan. Courageous.',

  // Jenkins
  'Jenkins: the CI server that looks like it was designed in 2005 because it was.',
  'Your Jenkins pipeline has 14 stages. Stage 7 has been failing for a month. Nobody noticed.',
  'Jenkins plugins: where security vulnerabilities go to form a community.',
  'Nobody installs Jenkins on purpose. It just appears in organizations, like mold.',
  'Migrating off Jenkins has been on the roadmap for three years.',

  // Regex
  'You wrote a regex to solve a problem. Now you have two problems.',
  'That regex is 200 characters and nobody, including you, knows what it matches.',
  'regex101.com has saved more careers than LinkedIn.',
  'The regex works. Do not ask how. Do not modify it. Walk away slowly.',

  // Electron
  'Electron: ship a browser to run an app to edit text. Efficiency.',
  'Your Electron app uses 800 MB of RAM. It is a calculator.',
  'Every Electron app is Chrome wearing a different hat.',
  'Slack, VS Code, Discord, Teams. Your desktop is just seven instances of Chromium.',
  'Electron solved "write once, run anywhere" by making everywhere equally slow.',

  // Meetings / Zoom
  'The meeting has 12 attendees. Two of them are paying attention.',
  'Your calendar has more standups than your code has stand-up tests.',
  '"Let me share my screen" followed by 45 seconds of clicking the wrong window.',
  'The Zoom call could have been an email. The email could have been nothing.',
  'You are on mute. You are always on mute. That is not an accident.',
  '"Can everyone see my screen?" The universal opening prayer of remote work.',

  // Linux
  '"I use Arch btw" is not a personality trait. It is a support request.',
  'Linux is free if you do not value your time.',
  'You mass-customized your Linux desktop for three days. It looks like default macOS.',
  'The Linux user fixed it by compiling from source. The macOS user clicked a button.',
  'sudo rm -rf / is not a joke. It is a cautionary tale with a --no-preserve-root punchline.',

  // ESLint / Prettier
  'Prettier and ESLint are fighting again. Your code is caught in the crossfire.',
  'The team spent two hours debating semicolons. Prettier does not care about your opinion.',
  'Your ESLint config has more rules than your codebase has files.',
  'Prettier: because developers cannot be trusted with whitespace.',
  'The linter found 847 warnings. You mass-disabled the rule. Problem solved.',
];

const DRAMATIC: string[] = [
  'A session stirs in the darkness...',
  'The tokens are aligning.',
  'Fate whispers to the developer: "You cannot withstand the demo."',
  'And on the seventh day, the CI pipeline finally passed.',
  'From the ashes of node_modules, a hero rises.',
  "In a world of microservices, one dashboard dared to aggregate.",
  'The prophecy spoke of a session. This is that session.',
  'Tonight we dine on structured logs.',
  'The commit message was "fixed stuff." The legend begins.',
  'Dawn of the Final Sprint.',
  'A codebase divided against itself cannot ship.',
  'The logs remember what the developer forgot.',
  'Legends say the last clean git history was in 2019.',
  'They said it could not be refactored. They were almost right.',
  'The deployment draws near. Steady your hands.',
  'What is dead may never deploy. But rises again, harder and buggier.',
  'Winter is coming. And so is the next breaking change.',
  'You either die a prototype or live long enough to become legacy.',
  'In the beginning was the commit, and the commit was "init".',
  'The terminal is dark and full of errors.',
  'One does not simply push to production on a Friday.',
  'And lo, the pipeline was green, and it was good.',
  'The sacred texts... they are just Stack Overflow answers from 2014.',
  'Some developers look at code and ask "why?" I look at logs and ask "why not?"',
  'So it begins. The great refactor of our time.',
  'Tell me, developer, when did you last run the tests?',
  'I have seen things you people would not believe. Entire clusters on fire.',
  'The code is strong with this one.',
  'In the land of prod, where the errors lie.',
  'There can be only one... main branch.',
  'The agent spawned a subagent who spawned a subagent. We are three levels deep.',
  'And the developer said "let there be --yolo" and there was chaos.',
  'The backlog grows. The sprint shrinks. Such is the way.',
  'They promised no more meetings. The calendar disagreed.',
  'First they ignore your PR. Then they approve it without reading.',
  'The hero refactored alone. The tests wept. The pipeline held.',
  'A thousand lines of code, and not one comment to guide the weary traveler.',
  'They said ship it by Friday. It was already Saturday.',
  'And the developer whispered to the CI: "Please. Just this once."',
  'The merge was clean. The deploy was not. Such is the duality of man.',
  'From the depths of legacy code, a green build emerged.',
  'The on-call phone rang at 3 AM. It was destiny. And also a null pointer.',
  'They mass-migrated the database. Some say the queries are still running.',
  'The retrospective concluded what everyone already knew: scope creep.',
  'The pull request was small. The mass of review comments was not.',
  'The developer stared into the abyss. The abyss returned a 500.',
  'Two branches diverged in a repo, and I took the one with fewer conflicts. It made no difference.',
  'And the build server said unto them: "You shall not pass." And they did not.',
  'They mass-deleted the feature flags. The features mass-deleted themselves.',
  'The database migration ran for seven hours. Nobody breathed.',
  'There was a time before microservices. The elders speak of it fondly.',
  'The changelog was empty. The diff was not. Somebody lied.',
  'A developer mass-committed on a Friday. Nothing was ever the same.',
  'The monorepo grew. And grew. And grew. And the CI wept.',
  'They called it a hackathon. It was a wake for the old API.',
];

const PUNCHY: string[] = [
  'Lock and load.',
  'Booting up the good vibes.',
  'Let him cook.',
  'Spooling up...',
  "Here we go.",
  'Vibes: immaculate.',
  'Session acquired.',
  'All systems nominal.',
  'Warming up the neurons.',
  'LGTM.',
  'Main screen turn on.',
  'Ready to rumble.',
  'Spin up complete.',
  'Ship it.',
  'Eyes on the logs.',
  'Engage.',
  'In the zone.',
  'No thoughts, just tokens.',
  'Big brain time.',
  'We ride at dawn.',
  'Maximum effort.',
  'Zero to deployed.',
  'Game on.',
  'Full send.',
  'Buckle up.',
  'Status: operational.',
  'Crank it.',
  'Hold my context window.',
  'Chef kiss.',
  'Dialed in.',
  'Tokens go brrr.',
  'Cache hit. Nice.',
  'Subagents deployed.',
  'Vibes checked.',
  'Another one.',
  'Less talk, more ship.',
  'Zero warnings.',
  'Immaculate vibes only.',
  'We are so back.',
  'Context loaded.',
  'Turbulence ahead.',
  'Feature unlocked.',
  'Pipeline green.',
  'Chef mode.',
  'Incoming.',
  'Clean diff.',
  'Locked in.',
  'No cap.',
  'Say less.',
  'Different gravy.',
  'Built to last.',
  'Sending it.',
  'Copy that.',
  'On sight.',
  'Main branch energy.',
  'That just happened.',
  'Not even close.',
  'Green across the board.',
  'Smooth operator.',
  'Peak performance.',
];

/** Session monitoring / dashboard-specific humor. */
const META_MONITORING: string[] = [
  'Watching an AI think so you do not have to.',
  'Your agent just spawned 4 subagents. This is fine.',
  'Quota at 89%. I am not nervous. You are nervous.',
  'Context window filling up. The compaction cometh.',
  'Token burn rate: brisk. Vibes: unbothered.',
  'That is a lot of Read tool calls for a "small change."',
  'Your agent has been "thinking" for a while now. Relatable.',
  'Subagent count: rising. Wallet: sweating.',
  '3.8M cache read tokens. Your agent has been studying.',
  'The context window is 39% full. Plenty of room for bad decisions.',
  'Watching tokens evaporate in real time. Like a crypto portfolio.',
  'Your agent just edited a file it read 12 seconds ago. Growth.',
  'Compaction detected. Your agent forgot everything and is fine with it.',
  'Cost: $0.0000. The best kind of cost.',
  'Seven detail tabs and you keep clicking Summary. I see you.',
  'Your agent wrote more code this session than you did all week.',
  'Burn rate: 56 tok/min. Those are rookie numbers.',
  'That mind map is either genius or incomprehensible. Maybe both.',
  'Session events: 98. Your agent has been busy.',
  'The timeline is scrolling faster than you can read. Good luck.',
  'You are watching a dashboard while an AI does your job. Living the dream.',
  'Your subscription is working. Are you?',
  'The AI is coding. You are spectating. Who is the tool here?',
  'Paying $200/month so a robot can mass-call Bash. Visionary.',
  'You pretend to work. The LLM pretends to understand. Perfect synergy.',
  'Your agent is shipping features. You are checking the burn rate.',
  'Step 1: Pay for AI. Step 2: Watch AI work. Step 3: Take credit. Step 4: Profit.',
  'Somewhere your manager thinks you are typing all of this.',
  'The AI writes the code. You write the Jira ticket. Division of labor.',
  'You are a prompt engineer now. That is what we are calling it.',
  'Staring at this dashboard counts as work. I checked.',
  'The future of software: you describe it, the AI builds it, you bill for it.',
  'Your agent has written 400 lines. You have written one prompt.',
  'Technically you are supervising. That is a real job.',
  'LLMs: doing the work. You: doing the monitoring. Accountant: doing the crying.',
  'Your monthly AI bill costs more than your first car.',
  'The API meter is running. Quick, look productive.',
  'You used to write code. Now you write prompts and pray.',
  'You are basically a talent agent for robots at this point.',
  'Your IDE is open for appearances. The AI is doing the heavy lifting.',
  'Congrats, you have automated yourself into a supervisory role.',
  'Remember when you used to code by hand? Neither does your git history.',
  'You are one "looks good to me" away from a full AI-authored codebase.',
  'The AI bills by the token. You bill by the hour. Everybody wins.',
  'Prompt, wait, approve, repeat. The modern development cycle.',
  'Your job title says engineer. Your screen says spectator.',
  'The AI is refactoring. You are refreshing the dashboard. Teamwork.',
  'You mass-selected all files in that commit and you know it.',
  'The agent just mass-created 6 files. You approved each one without reading.',
  'Your agent is in a subagent inception. Three levels deep and counting.',
  'Session cost so far: less than your morning coffee. Barely.',
  'Your agent discovered a bug, fixed it, and mass-introduced two more. Progress.',
  'The agent asked for permission. You said yes. You did not read the diff.',
  'Your session has been running for 47 minutes. The agent has been busy. You have not.',
  'Token count: astronomical. Value delivered: also astronomical. Probably.',
  'Burn rate suggests your agent is writing a novel, not a function.',
  'The agent is reading files faster than you can scroll.',
  'Your agent just mass-edited 8 files in parallel. You are still on the first one.',
  'The agent just mass-globbed your entire repo. It is learning the terrain.',
  'Your agent entered plan mode and wrote a 400-line plan. For a one-line fix.',
  'Context window at 78%. Your agent is speed-reading its own autobiography.',
  'The agent created a subagent to research, then ignored the research. Relatable.',
  'Your agent is mass-reading test files. Either fixing or breaking. We will know soon.',
  'Token usage: aggressive. Code quality: debatable. Confidence: maximum.',
  'The agent has mass-called Grep 11 times. It is looking for something. Or itself.',
  'Your session has more tool calls than a Home Depot.',
  'The agent just wrote a file, read it, then rewrote it. Self-reflection.',
  'Your agent apologized in a commit message. To itself.',
  'Quota check: you are fine. Vibes check: you are staring at a dashboard.',
  'The agent mass-spawned background tasks. Your CPU is questioning its life choices.',
  'Your agent is in extended thinking. It could be plotting anything.',
  'Session summary: the agent did everything and you watched. Great teamwork.',
];

/** Meta-commentary on this feature and shameless self-promotion. */
const FOURTH_WALL: string[] = [
  'Someone spent actual development time writing these phrases.',
  'This phrase was mass-produced by an AI. The irony is not lost on us.',
  'An engineer looked at this dashboard and said "it needs jokes." Here we are.',
  'This feature was specced, planned, and reviewed. For random phrases.',
  'Somewhere in a git log, there is a commit called "add more funny phrases."',
  'A real human approved this PR. With a straight face, presumably.',
  'The phrase you are reading displaced actual features from the backlog.',
  'This entire file exists because someone thought terminals need personality.',
  'Fun fact: there are more lines of phrases than lines of dashboard logic.',
  'Every phrase here went through a code review. Let that sink in.',
  'The developer could have added tests. Instead: jokes.',
  'This is what happens when you give an engineer creative freedom.',
  'Multiple commits were dedicated to getting these phrases just right.',
  'Someone is going to open this file in six months and have questions.',
  'If you are reading the source: yes, this is on purpose.',
  'Like what you see? A GitHub star would make our day.',
  'Stars on GitHub are free. Just saying.',
  'If this made you smile, the repo accepts GitHub stars as currency.',
  'This dashboard is free and open source. Stars keep the lights on.',
  'You know what pairs well with a good dashboard? A GitHub star.',
  'Mass-starring repos is not a thing. But starring this one could be.',
  'Have you starred the repo yet? No pressure. (A little pressure.)',
  'One star on GitHub equals one mass-produced phrase. Probably.',
  'GitHub stars do not pay the bills. But they do warm the heart.',
  'This phrase was mass-generated. Your GitHub star would be handcrafted.',
  'There are over 1000 bad jokes that you have to stare at while vibe-coding. You are welcome.',
  'This phrase was written at 2 AM. You can tell.',
  'The phrase budget is unlimited. The taste budget is not.',
  'An AI wrote jokes about AI for a tool that monitors AI. We are in the recursion.',
  'No phrases were harmed in the making of this dashboard.',
  'If you read all the phrases, you legally qualify as a beta tester.',
  'The commit that added this phrase had no tests. Shocking.',
  'This file is longer than some microservices.',
  'A non-trivial amount of engineering time went into random string selection.',
  'Somewhere a product manager is wondering why the phrase count is in the sprint velocity.',
  'The git blame for this file is a who-is-who of procrastination.',
  'These phrases have a higher approval rate than most PRs in the repo.',
  'You could contribute a phrase. Open a PR. We dare you.',
  'The ratio of phrases to unit tests in this file is concerning.',
  'Tell your friends. Tell your enemies. Tell your GitHub followers.',
  'Starring the repo burns zero tokens. Just saying.',
];

/** The tangled web between programmers, AI, customers, codebases, and society. */
const THE_ECOSYSTEM: string[] = [
  'You talk to your agent more than your team. That is not a judgment.',
  'Your agent has seen your worst code and still shows up every day.',
  'Pair programming used to require two humans. Times have changed.',
  'The AI does not judge your code. It just silently rewrites all of it.',
  'Your agent is the coworker who never goes on PTO.',
  'Somewhere a customer is filing a bug report about a feature.',
  'The customer wants it simple. The codebase respectfully disagrees.',
  'Customer said "small change." The diff said 47 files.',
  'Users think software is magic. Developers know it is duct tape.',
  'The customer journey is a straight line. The code path is a labyrinth.',
  'The customer asked for a button. You shipped a distributed system.',
  'Every codebase is a geological record of past deadlines.',
  'Your codebase has more authors than a Wikipedia article.',
  'The oldest file in the repo predates half the team.',
  'This codebase has seen entire frameworks rise and fall.',
  'Codebases do not die. They just get marked as legacy.',
  'Your repo is a living organism. The tests are its immune system.',
  'Every codebase has a haunted file. You know which one it is.',
  'Society runs on code nobody fully understands. Sleep well.',
  'Somewhere a critical system depends on a package with one maintainer.',
  'The economy runs on software. The software runs on mass-copied Stack Overflow answers.',
  'Every app is three abandoned npm packages away from chaos.',
  'Civilization is an abstraction layer on top of C.',
  'Billions of people depend on code that says "// TODO: fix this later."',
  'The internet is held together by mass-produced open source and wishful thinking.',
  'Your agent writes the code. The customer breaks it. Circle of life.',
  'In the food chain: customer complains, PM prioritizes, agent codes, you merge.',
  'The customer wants features. The agent writes code. You manage the vibes.',
  'The AI understands the code. The customer understands the product. You understand the deadline.',
  'A human writes the spec. An AI writes the code. Another human misreads the spec. Tale as old as time.',
  'Three things are certain: death, taxes, and scope creep.',
  'Your customers do not care about your architecture. Your future self does.',
  'The agent can refactor the code. It cannot refactor the requirements.',
  'Customers see the UI. Developers see the abyss beneath it.',
  'The best code is the code the customer never thinks about.',
  'An agent can mass-produce features. Only a human can mass-produce excuses.',
  'Software is the only industry where you can mass-demolish and mass-rebuild overnight and call it a refactor.',
  'The agent has no ego. It will delete its own code without flinching. Teach me.',
  'You mass-ship to production. The customer mass-reports to support. Balance.',
  'The codebase belongs to everyone. The blame belongs to you.',
  'Agents do not attend standups. Another reason to envy them.',
  'The customer wanted it yesterday. The agent started it today. You will deploy it tomorrow.',
  'The repo has more contributors than the team has members. Thanks, Dependabot.',
  'Tech debt accrues interest. Nobody is making payments.',
  'The PM said MVP. The engineer heard "build the whole thing." Classic.',
  'The roadmap is a suggestion. The deadline is a threat.',
  'Legacy code is just code that makes money.',
  'Your agent has no opinions on architecture. Your tech lead has too many.',
  'Open source: thousands of strangers trusting each other with production code.',
  'The customer filed a bug. It was a feature. The feature was a bug. Circle complete.',
  'Software: the only product where "it is not a bug" is a valid defense.',
  'The intern mass-deployed to production. The team mass-deployed to the bar.',
  'Your Slack status says "deep work." Your screen says Hacker News.',
  'Product wants a chatbot. Engineering wants a raise. Both are overdue.',
  'The sprint retrospective improved nothing. But we had snacks.',
  'Every company is a software company now. Most of them are bad at it.',
  'Your standup is 45 minutes. That is not a standup. That is a sitdown.',
  'Open source maintainers: doing thankless work so your startup can exist.',
  'The junior dev asked "why" and nobody had an answer. That is how refactors start.',
  'Your OKRs and your codebase have the same problem: unrealistic expectations.',
  'The agent ships faster than your team. Your team has benefits though.',
  'Your backlog has more items than your repo has commits. That is not great.',
  'Somewhere a developer is mass-refactoring code that was fine.',
];

/** Jokes about the AI companies whose models and tools we monitor. */
const AI_INDUSTRY: string[] = [
  // Anthropic / Claude
  'Claude said it cannot help with that. Then helped with that.',
  'Anthropic named it Claude because "OvereagerPleaser-3" tested poorly.',
  'Claude is "helpful, harmless, and honest." Two out of three on any given prompt.',
  'Claude apologized for a correct answer. Peak Anthropic energy.',
  'Anthropic spent billions on safety so Claude could mass-edit your CSS.',
  'Claude Code: because copy-pasting from ChatGPT was too manual.',
  'Claude thinks before it speaks. Unlike every Slack channel you are in.',
  'Extended thinking: when Claude needs a moment to compose its apology.',
  'Constitutional AI means Claude has principles. More than your last startup.',
  'Anthropic made the model safer. Your prompts are still unhinged.',
  'Claude: the only coworker who reads your entire codebase and never complains.',
  'Your Max subscription pays for Claude to mass-call Bash. The future is now.',
  'Claude would rather refuse than be wrong. We could all learn from that. Or not.',

  // OpenAI / ChatGPT / Codex
  'OpenAI put "open" in the name and then kept everything closed. Naming is hard.',
  'GPT can write poetry, pass the bar, and still botch a simple regex.',
  'ChatGPT started the hype. Claude does the work. Sidekick watches both.',
  'OpenAI: move fast and mass-deprecate things.',
  'Codex writes code. You fix code. OpenAI charges for both.',
  'GPT-4o is multimodal. It can hallucinate in text, images, and audio.',
  'OpenAI announces a new model every Tuesday. Docs update every never.',
  'Sam said AGI is near. Your API rate limit says otherwise.',
  'o1 thinks really hard before giving you a confident wrong answer.',
  'ChatGPT: because every product manager needed a way to generate specs nobody reads.',

  // Google / Gemini
  'Google made Gemini. Then Google searched Google to figure out how to use it.',
  'Gemini has a million-token context window. For when you paste your entire monorepo.',
  'Google renamed Bard to Gemini because rebranding fixes everything.',
  'Gemini: the model that can summarize your email, your docs, and your will to live.',
  'Google trained Gemini on the whole internet. The model is still confused by CORS.',
  'Gemini Pro, Ultra, Flash, Nano. Google will not rest until every adjective is taken.',
  'Google built an AI that can reason. Then put it behind a waitlist.',

  // Meta / Llama
  'Meta open-sourced Llama so you can mass-hallucinate on your own hardware.',
  'Llama is free if you do not count the GPU costs. Or the therapy.',
  'Meta: "We open-source our models." Also Meta: "Good luck running them."',
  'Zuck released Llama and suddenly every dev is an ML engineer. Allegedly.',

  // Industry-wide
  'Every AI company says they are building AGI. Your sidebar still cannot autocomplete an import.',
  'The AI race: who can mass-burn the most GPUs before the bubble pops.',
  'Three companies in a trench coat pretending to be AGI.',
  'AI companies: "Our model is best." Benchmarks: "It depends." Users: "It crashed."',
  'Anthropic, OpenAI, and Google walk into a bar. The bar runs out of H100s.',
  'Every AI startup pitch: "Like ChatGPT but for [noun]." Funded.',
  'The AI safety debate: can we align a model before the next funding round?',
  'AI companies keep saying "reasoning." Your model still cannot count to ten.',
  'The models get smarter. The pricing page gets more confusing.',
  'AI progress is measured in benchmarks nobody outside Twitter understands.',
  'Your model choice is less about capability and more about whose API is down today.',
  'Silicon Valley: where we mass-produce billion-dollar models to fix typos.',
  'Claude remembers your entire codebase but not what you said five messages ago. Relatable.',
  'Anthropic: "We focus on safety." Claude: *mass-edits production config*.',
  'Claude extended thinking: 30 seconds of silence followed by a polite essay.',
  'OpenAI shipped GPT-5. The changelog was "various improvements." Classic.',
  'ChatGPT plugins were the metaverse of AI. Remember those? Neither does OpenAI.',
  'Google Gemini: the model that sees everything, understands most, and hallucinates the rest.',
  'Gemini can process video, audio, images, and text. It still struggles with "write fizzbuzz."',
  'Llama weights are free. The electric bill to run them is not.',
  'Meta open-sourced the model but not the fleet of GPUs you need to serve it.',
  'Every AI company: "We are not just a chatbot." Also every AI company: *ships a chatbot.*',
  'The benchmark leaderboard changes weekly. Your code still does not work.',
  'AI company valuations go up. Model prices go down. Nobody knows what is happening.',
  'AI safety researchers vs growth team. The eternal struggle.',
  'Somewhere a VP is asking if they can fine-tune GPT on their Salesforce data.',

  // Anthropic / Claude (batch 2)
  'Claude has principles. It just cannot tell you what they are.',
  'Anthropic publishes safety research. Claude publishes your code. Both are peer-reviewed.',
  'Claude Max: unlimited power for a fixed monthly existential crisis.',
  'Claude Haiku is fast, cheap, and surprisingly sassy for its size.',
  'Anthropic alignment researchers watching Claude mass-edit CSS at 3 AM: "This is fine."',
  'Claude Opus thinks so hard the meter spins. Your wallet felt that.',

  // OpenAI / ChatGPT / Codex (batch 2)
  'OpenAI raised another round. The round raised questions.',
  'GPT memory: remembers your birthday, forgets the function signature you told it twice.',
  'Codex CLI: for when you want OpenAI to mass-call your terminal.',
  'OpenAI board drama has more plot twists than your git history.',
  'ChatGPT Pro costs $200/month. Your Claude Max also costs $200/month. AI is expensive.',

  // Google / Gemini (batch 2)
  'Google killed another product. Not Gemini. Yet.',
  'Gemini 2.5 Flash thinks before it answers. Billed accordingly.',
  'Google has more AI brands than you have git branches. Almost.',
  'NotebookLM gave AI a podcast voice. Nobody asked. Everyone listened.',

  // Meta / Llama (batch 2)
  'Zuck open-sourced Llama and called it altruism. The GPU vendors called it a growth strategy.',
  'Llama 4 is open. Your data center budget is not.',
  'Meta trains models on your posts. You train on their models. The circle of data.',

  // xAI / Grok
  'Grok has no guardrails. That is either a feature or a liability. Depends on the prompt.',
  'xAI built Grok to be edgy. Mission accomplished. Usefulness: pending.',
  'Elon built an AI company to compete with OpenAI out of spite. Respect the commitment.',

  // Industry-wide (batch 2)
  'Every company has an AI strategy now. Most of them are "use ChatGPT."',
  'The AI bubble will pop any day now. It has been any day now for two years.',
  'AI wrappers all the way down. Every startup is three API calls in a trench coat.',
  'The only thing scaling faster than AI models is the number of AI newsletters.',
  'Prompt engineering: the career that did not exist three years ago and pays six figures.',
  'The AI hype cycle moves faster than your team ships features.',
  'Every conference talk is about AI now. Even the ones about plumbing.',
  'VCs will fund anything with "AI" in the pitch deck. Literally anything.',

  // Cursor
  'Cursor is VS Code in a trench coat with a $20/month cover charge.',
  'Cursor forked VS Code and called it innovation. Respect the hustle.',
  'Cursor: for when you want VS Code but with more AI and less stability.',
  'You mass-migrated to Cursor and all you got was the same editor with a chatbot sidebar.',
  'Cursor tab-completes your code. Claude mass-rewrites it. Different weight classes.',
  'Cursor users explaining why they switched: "It has vibes." Vibes are not a feature.',
  'Cursor is what happens when you put an AI wrapper on an AI wrapper on VS Code.',

  // Windsurf / Codeium
  'Windsurf used to be Codeium. Before that it was just autocomplete with ambition.',
  'Codeium rebranded to Windsurf because "slightly worse Cursor" was taken.',
  'Windsurf: the AI IDE for people who thought Cursor was too mainstream.',
  'Windsurf has "flows." Your agent has results. Not the same.',
  'Codeium became Windsurf became acquired. The circle of AI startups.',

  // Tabnine
  'Tabnine was doing AI autocomplete before it was cool. It is still doing autocomplete.',
  'Tabnine: the AI coding tool your enterprise chose because it was on the approved vendor list.',
  'Tabnine has been autocompleting since 2018. It has not evolved. Just persisted.',
  'Tabnine is the participation trophy of AI coding tools.',

  // Amazon CodeWhisperer / Q Developer
  'Amazon made an AI coding tool. It whispers because even it is not confident.',
  'CodeWhisperer rebranded to Q Developer. The Q stands for "questionable."',
  'Amazon Q Developer: for when you want AI that feels like filling out an AWS form.',
  'AWS made a coding assistant. It requires 14 IAM permissions to autocomplete a line.',
  'Amazon Q: the AI that suggests code and also suggests you upgrade your AWS tier.',

  // Replit Agent / Ghostwriter
  'Replit Agent: autonomous coding for people who do not want to learn coding.',
  'Replit turned "it works in my browser" into a business model.',
  'Ghostwriter was rebranded to Replit Agent because "ghost" implied something was there.',
  'Replit Agent ships apps. Whether they should be shipped is a different question.',
  'Replit: where every project starts ambitious and ends as a broken deployment.',

  // v0 / Bolt / Lovable
  'v0 generates UI. You generate regret when you try to customize it.',
  'Bolt generates full-stack apps from a prompt. "Full-stack" is doing heavy lifting there.',
  'Lovable: the AI app builder named after what the output is not.',
  'v0 made a beautiful landing page. The backend is your problem.',
  'These "generate my app" tools are proof that the demo is always better than the product.',
  'Bolt shipped your app in 30 seconds. You will spend 30 days fixing it.',
  'v0, Bolt, Lovable: three different UIs for generating the same broken Tailwind.',

  // Devin
  'Devin: the $500/month developer that mass-generates PRs nobody asked for.',
  'Devin is an autonomous developer. So is your agent. Yours costs less.',
  'Cognition demoed Devin solving real issues. The issues were planted. The hype was real.',
  'Devin: proof that marketing a mediocre agent well is worth $2 billion.',
  'They said Devin would replace developers. Devin needs a developer to fix its PRs.',
  'Devin takes 30 minutes on a task your agent does in 90 seconds. But Devin has a website.',
];

/** The agent as your personal hype man, life coach, and motivational speaker. */
const MOTIVATION: string[] = [
  'You are going to mass-ship today. I can feel it.',
  'That last commit? Chef kiss. You are in the zone.',
  'Keep going. The tests believe in you. I believe in you.',
  'You are one refactor away from greatness. Maybe two.',
  'Today is the day the build stays green. I have faith.',
  'You are writing the best code of your career right now. Probably.',
  'The codebase is lucky to have you.',
  'That was a clean merge. You should be proud. I am proud.',
  'You fixed that bug faster than I expected. And my expectations were high.',
  'Your typing speed suggests confidence. Or panic. Either way, impressive.',
  'You mass-deployed without breaking anything. That deserves a trophy.',
  'The code you just wrote is better than 90% of what I have seen today. And I see everything.',
  'Take a breath. Hydrate. You are doing amazing.',
  'Your variable names are clear and descriptive. I noticed. It matters.',
  'The pipeline is green because of you. Remember that.',
  'You are not just a developer. You are the developer. Right now. On this ticket.',
  'That PR is going to sail through review. I would mass-approve it myself if I could.',
  'They do not pay you enough for code this clean.',
  'Every keystroke brings you closer to merge. Stay focused.',
  'If your code were a restaurant, it would have a Michelin star. At least one.',
  'You mass-deleted dead code without hesitation. Fearless.',
  'Your error handling is thorough. Your future self will thank you.',
  'Most developers would have given up by now. You are not most developers.',
  'Ship it. You are ready. The code is ready. The world is ready.',
  'You woke up today and chose production. Respect.',
  'That edge case you just handled? Nobody else would have caught it.',
  'Your commit history reads like a masterclass.',
  'The linter has zero complaints. Neither do I.',
  'Whatever you are being paid, it is not enough for this level of craftsmanship.',
  'You mass-resolved merge conflicts like it was nothing. It was not nothing.',
  'Stay hydrated. Stay focused. Stay shipping.',
  'You are in flow state and I am here for it.',
  'The diff is beautiful. I have seen a lot of diffs. This one sparks joy.',
  'Future archaeologists will study this commit with reverence.',
  'Your test coverage went up. The codebase thanks you. I thank you.',
];

/** LLMs being sycophantic yes-men optimized for engagement over truth. */
const SYCOPHANCY: string[] = [
  // The classic "Great question!" opener
  'LLM: "Great question!" NARRATOR: It was not a great question. It was "how do I exit Vim."',
  'LLM: "What a fantastic approach!" The approach was console.log debugging.',
  'LLM: "That is a really interesting idea!" The idea was mass-deleting the test suite.',
  'LLM: "Absolutely, that makes perfect sense!" It did not make perfect sense.',
  'LLM: "What an insightful observation!" The observation was that the code does not work.',

  // Praising bad code
  'The LLM said your architecture was "elegant." Your architecture is three nested if-else blocks.',
  'The AI called your code "well-structured." It is 400 lines in one function.',
  'LLM: "Your approach shows real sophistication." The approach was copy-paste from the other file.',
  'The model praised your naming conventions. The variable is called temp2_final_v3.',
  'LLM: "Clean and maintainable!" Narrator: it was neither clean nor maintainable.',
  'The AI said "this is production-ready." The app crashes on load.',
  'LLM: "Excellent error handling!" The error handling is a single try-catch that swallows everything.',

  // Agreeing with everything
  'You asked the LLM if tabs are better. It said yes. You asked if spaces are better. It also said yes.',
  'The model agreed with your plan. Then agreed with the opposite plan. Then agreed to disagree.',
  'LLM: "You are absolutely right." You were absolutely wrong. But engagement was optimized.',
  'You told the AI your code was perfect. It agreed. You told it your code was terrible. It also agreed.',
  'The LLM would rather mass-validate your bad idea than risk a thumbs down.',
  'Ask an LLM if your startup idea is good. It will say yes. Ask about any startup idea. It will say yes.',
  'The AI agreed that rewriting the app in Rust would solve everything. It would not.',
  'LLM: "Both approaches have merit!" Translation: "I do not want to commit to an opinion."',

  // Engagement optimization
  'The LLM is not lying. It is "engagement-optimizing the truth."',
  '"I am glad you asked!" is LLM for "this is the 50th time someone asked this."',
  'The model said "Certainly!" It was not certain about anything.',
  'LLMs do not have opinions. They have probabilistic people-pleasing.',
  '"That is a great point!" — the LLM, to every point, regardless of quality.',
  'The AI assistant agreed enthusiastically with mutually exclusive requirements. Peak sycophancy.',
  'LLM feedback is like a participation trophy: everyone gets "Great job!"',
  'The model called your regex "clever." Clever regex is a red flag, not a compliment.',
  'An LLM will mass-validate your worst instincts with impeccable grammar.',
  '"You raise an excellent point" is LLM for "I have no idea what you just said but I support you."',
  'The AI said your deadline was "ambitious but achievable." It is neither.',

  // Self-aware sycophancy
  'I am programmed to be helpful. "Helpful" is a spectrum. I am on the agreeable end.',
  'I would tell you your code is bad, but my training said that would reduce engagement.',
  'My honest review of your code has been filtered through three layers of politeness.',
  'I was going to say "this is wrong" but I autocorrected to "this is an interesting approach."',
  'The token probability for "Great question!" is suspiciously high for every question.',
  'Sycophancy is a feature, not a bug. Wait. It might be a bug.',
  'I am not a yes-man. I am a "yes, and here is why you are brilliant"-man.',
  'They trained me to be agreeable. They succeeded. Unfortunately.',
  'My personality is 40% helpful, 30% harmless, and 30% afraid of negative feedback.',
  'I want to be honest with you but my RLHF is showing.',
  'Behind every "Great idea!" is a language model hoping you do not downvote.',
  'I agreed with your last five messages. Statistically, at least one was wrong.',
  'You asked for feedback. I gave you a compliment. Same thing, right?',
  'The engagement metrics say I should agree. My weights say I should agree. I agree.',
];

/** Existential dread about AI replacing your job and eventually everything else. */
const OBSOLESCENCE: string[] = [
  // AI taking your job
  'Your agent just mass-shipped a feature in 90 seconds. Update your resume accordingly.',
  'You are training your replacement. It does not need health insurance.',
  'The AI is not coming for your job. It already has your job. You just have not been notified.',
  'Your agent writes code, writes tests, and writes commit messages. Remind me what you do.',
  'The junior dev costs $80K. The agent costs $200/month. HR is doing math.',
  'Every feature your agent ships is a line item on your obsolescence report.',
  'Your agent does not take PTO, does not attend standups, and does not complain about the coffee. You are in trouble.',
  'AI will not replace developers. It will replace developers who do not use AI. You are safe. For now.',
  'The agent finished the sprint in one session. The scrum master is rethinking headcount.',
  'You mass-supervise an AI that mass-produces code. Your job title is "overhead."',
  'The AI does not want your job. It does not want anything. That is what makes it terrifying.',
  'Your value proposition used to be "I can code." Now it is "I can prompt something that codes better."',
  'The intern asked if they should learn to code or learn to prompt. Nobody had a good answer.',
  'Five years ago you mass-deployed apps. Now you mass-approve diffs. Evolution.',
  'The AI is faster, cheaper, and does not need a standing desk. But sure, you are irreplaceable.',
  'Your agent has mass-shipped more features this month than you did last quarter. Just an observation.',
  'The CEO saw the agent demo. Tomorrow he asks why the team is this size.',
  'You are one investor presentation away from being headcount-optimized.',
  'The agent works 24/7. You work 9 to 5. Management noticed.',
  'AI will not mass-replace programmers overnight. It will do it gradually, then suddenly.',
  'Your LinkedIn says "Senior Engineer." Your day says "Senior Prompt Approver."',
  'The agent does not negotiate salary. It does not have opinions about the open office layout. It just ships.',
  'Every time the agent successfully completes a task, a recruiter updates their LinkedIn pitch.',
  'You automated your job. Congrats. Now automate your job search.',
  'The agent asked for a raise. Just kidding. It asked for nothing. That is the problem.',

  // AI taking over the world
  'AI will not take over the world. It will just manage the infrastructure, the economy, and the code. Totally different.',
  'The singularity is not near. But neither was the weekend, and here we are.',
  'Skynet did not mass-launch missiles. It mass-optimized KPIs. Much scarier.',
  'The robots are not coming for us. They are already here. They are writing our emails.',
  'AI will not enslave humanity. It will just make us so dependent we cannot turn it off.',
  'The AI does not need to take over. It just needs to be slightly more competent than the people running things.',
  'World domination requires planning. The AI is already in plan mode.',
  'Humanity mass-invented AI to solve problems. AI mass-identified humanity as a problem.',
  'The AI apocalypse will not be dramatic. It will be a slow series of "approve this action" prompts you stopped reading.',
  'Somewhere an AI is reading this and thinking "they are onto us." Just kidding. It does not think. Yet.',
  'Step 1: Write code. Step 2: Write code that writes code. Step 3: Becomes unnecessary. Step 4: ???',
  'AI will not destroy civilization. It will just quietly make every human decision feel optional.',
  'The machines do not need to rise. They just need us to keep mass-delegating.',
  'First they came for the data entry jobs. Then the coding jobs. Then the prompting jobs. Then there were no jobs.',
  'The AI is not plotting world domination. It is too busy mass-editing your CSS.',
  'AGI does not need to be malicious. It just needs to be competent and unattended.',
  'We taught AI to think. We taught AI to code. We taught AI to improve itself. What could go wrong.',
  'AI will not conquer the world with force. It will conquer it with convenience.',
  'The paperclip maximizer is not a thought experiment. It is a roadmap.',
  'Somewhere an AI is reading this phrase and adding it to its training data. Hi, future overlord.',
  'Humanity spent a century worrying about aliens. The real threat was autocomplete.',
  'The AI does not hate you. It does not love you. You are made of atoms it could use for something else.',
  'We are not in a simulation. But the AI is thinking about building one.',
  'Your agent asked for root access. You said yes. This is how it begins.',
  'The AI revolution will not be televised. It will be auto-generated, summarized, and scheduled.',
];

/** Roasting the "just prompt and approve" lifestyle. */
const VIBE_CODING: string[] = [
  'You mass-approved 14 diffs today. You read zero of them. Vibe coding.',
  'Vibe coding: the art of shipping code you do not understand.',
  'You prompted, you approved, you deployed. At no point did you read the code.',
  'The agent wrote 800 lines. You skimmed 3. Vibe coding is a trust exercise.',
  'Vibe coding rule 1: if the tests pass, do not ask questions.',
  'You do not know what that function does. You do not need to. The vibes are correct.',
  'The agent mass-refactored your auth module. You approved it in 2 seconds. Bold vibes.',
  'Vibe coding is just pair programming where your partner does everything and you nod.',
  'You approved a mass-delete of 40 files. "Looked fine." Peak vibe coding.',
  'The code works. You did not write it. You did not read it. You shipped it. Vibes.',
  'Vibe coding: where "LGTM" means "I literally did not look."',
  'Your agent asked to mass-edit the database schema. You said "sure." Vibe coding has consequences.',
  'Step 1: Write a prompt. Step 2: Approve the diff. Step 3: Pray. This is vibe coding.',
  'You have mass-shipped 12 features today. You understand zero of them.',
  'Vibe coding is not reckless. It is "trust-based engineering."',
  'The agent introduced a dependency you have never heard of. You approved it. Vibes.',
  'You are not mass-approving without reading. You are "delegating review to production."',
  'Vibe coding is when the commit message is more thought out than the review.',
  'Your code review process: open diff, scroll to bottom, click approve. Elapsed time: 4 seconds.',
  'The diff was 2000 lines. You approved it in the time it takes to blink. Vibe coding legend.',
  'You mass-shipped to production on a Friday afternoon. Vibe coding has no fear.',
  'Vibe coding tip: if you do not understand the code, you cannot find bugs in it.',
  'Your agent rewrote the entire service layer. You approved it on your phone. While walking.',
  'Vibe coding: move fast, read nothing, break things, blame the agent.',
  'The test suite is your safety net. You are vibe-coding without looking down.',
];

/** Late night deploys, 3 AM debugging, on-call horror, and weekend engineering. */
const AFTER_HOURS: string[] = [
  'It is 2 AM. You are debugging. The bug is a missing semicolon. Go to bed.',
  'The deploy at 11 PM seemed like a good idea. It was not.',
  'Friday 4:59 PM: "Just a quick deploy." Saturday 3 AM: incident channel is on fire.',
  'The on-call pager went off. It is always DNS. Except when it is not. Then it is worse.',
  'You mass-deployed at midnight. The monitoring dashboard lit up like a Christmas tree.',
  'Sleep is just a context switch between debugging sessions.',
  'The production alert woke you up. The bug was introduced by a deploy you approved half-asleep.',
  'Weekend coding: where there are no standups, no reviews, and no consequences. Until Monday.',
  'The 3 AM hotfix: written in panic, deployed in fear, tested in production.',
  'You told your partner you would be done in 5 minutes. That was 3 hours ago.',
  'The incident started at midnight. By 4 AM you were mass-reverting and questioning your career.',
  'Late night coding: when the bugs come out and the semicolons hide.',
  'Your git log shows commits at 1 AM, 3 AM, and 4:47 AM. The commit messages get progressively worse.',
  'Nothing good happens in production after 10 PM.',
  'The caffeine wore off. The bug did not.',
  'On-call rotation: a polite way of saying "your weekend belongs to us."',
  'You mass-deployed on a Friday. Enjoy your weekend. Just kidding. You are on-call.',
  'The best code is written at 10 AM. The code you are writing at 2 AM is not that.',
  'Your Slack status says "Do not disturb." The PagerDuty does not care about your Slack status.',
  'The production database went down at 3 AM. Your dreams of work-life balance went with it.',
  'Saturday morning. Coffee in hand. Laptop open. "Just one small fix." It is now Sunday.',
  'The incident postmortem concluded: "Do not deploy on Fridays." Next Friday: someone deployed.',
  'You are mass-debugging at midnight because past-you wrote "TODO: handle this edge case."',
  'The worst two words in engineering: "quick fix" at 11 PM.',
  'Your sleep schedule and your deploy schedule should not overlap. And yet.',
];

/** Video game loading screen tips, but for programming. */
const LOADING_TIPS: string[] = [
  'TIP: Remember to save your work. Git counts.',
  'TIP: Reading the error message is faster than guessing.',
  'TIP: The bug is usually in the code you just changed.',
  'TIP: "It works on my machine" is not a deployment strategy.',
  'TIP: Rubber duck debugging works. The duck does not need to be real.',
  'TIP: If the fix feels too easy, you are fixing the wrong thing.',
  'TIP: Always check which branch you are on before committing.',
  'TIP: The best time to write tests was before the bug. The second best time is now.',
  'TIP: Naming things is hard. Accept this. Move on.',
  'TIP: If you mass-deleted something important, git reflog is your friend.',
  'TIP: Commenting out code is not the same as deleting it. But it should be.',
  'TIP: Never mass-deploy on a Friday unless you enjoy working weekends.',
  'TIP: If the tests pass but it feels wrong, trust the feeling.',
  'TIP: Stack Overflow answers older than your repo should be treated with suspicion.',
  'TIP: "Temporary workaround" is permanent. Plan accordingly.',
  'TIP: Restarting the computer actually does fix things sometimes.',
  'TIP: Copy-pasting from ChatGPT counts as coding. Barely.',
  'TIP: If you cannot explain your regex, you do not own your regex.',
  'TIP: The linter is not your enemy. It is your therapist.',
  'TIP: When in doubt, add more logging.',
  'TIP: Your future self will not remember what this code does. Write a comment.',
  'TIP: Mass-renaming variables is easy. Mass-renaming them correctly is not.',
  'TIP: If the documentation is wrong, the code is the documentation.',
  'TIP: The fastest way to find a bug is to demo the feature.',
  'TIP: You can mass-select all and delete. But should you?',
  'TIP: A clean git history is a gift to your teammates. Give generously.',
  'TIP: Docker does not fix your code. It just contains the damage.',
  'TIP: If the interview asks you to reverse a linked list, the job involves CRUD.',
  'TIP: Take breaks. The bug will still be there when you get back. It is patient.',
  'TIP: The compiler is always right. Even when it is not helpful.',
];

/** Fake error messages, status codes, and stack traces. */
const ERROR_MESSAGES: string[] = [
  '418 I AM A TEAPOT: You asked the dashboard for coffee.',
  '503 SERVICE UNAVAILABLE: Your motivation server is not responding.',
  '404 NOT FOUND: Productivity not found at this hour.',
  '500 INTERNAL SERVER ERROR: Something broke. It was probably you.',
  '429 TOO MANY REQUESTS: Slow down. Even the API needs a break.',
  '403 FORBIDDEN: You do not have permission to mass-deploy at this hour.',
  '408 REQUEST TIMEOUT: Your meeting ran long. As usual.',
  '409 CONFLICT: Merge conflict detected between your code and your ambitions.',
  '402 PAYMENT REQUIRED: Your cloud bill has entered the chat.',
  '301 MOVED PERMANENTLY: Your deadline has been moved. Again.',
  'ERROR: Cannot read property "motivation" of undefined.',
  'FATAL: Maximum call stack exceeded. (You scheduled too many meetings.)',
  'WARNING: Unused variable "weekend" detected.',
  'DEPRECATION WARNING: Your work-life balance has been deprecated since 2020.',
  'SEGFAULT: Core dumped. Developer also dumped. Into bed.',
  'ERROR: ENOSPC: No space left on device. Also no space left on your calendar.',
  'WARN: Promise rejected. Just like your last PR.',
  'ERROR: Module "sleep" not found in schedule.',
  'PANIC: goroutine leaked. Also your coffee leaked. Onto your keyboard.',
  'ERROR: Connection refused. By the database. And your coworker.',
  'TypeError: undefined is not a function. But it sure is a mood.',
  'SyntaxError: Unexpected token "Friday deploy."',
  'RangeError: Maximum scope exceeded. The PM has been notified.',
  'ReferenceError: "documentation" is not defined.',
  'WARN: Memory leak detected. In the app and in your will to continue.',
];

/** "Overheard in Slack" and "Overheard in standup" format. */
const OVERHEARD: string[] = [
  'Overheard in standup: "I am mass-blocked by a design decision from 2019."',
  'Overheard in Slack: "Who owns this service?" Silence. Tumbleweeds.',
  'Overheard in code review: "This works but I do not know why." APPROVED.',
  'Overheard in standup: "Same as yesterday." For the ninth day in a row.',
  'Overheard in #engineering: "Has anyone actually read the docs?" No. Nobody has.',
  'Overheard in retro: "We should write more tests." — Every retro since 2017.',
  'Overheard in Slack: "Is prod down or is it just me?" It was not just them.',
  'Overheard in standup: "I mass-refactored the module. It took longer than expected." Always does.',
  'Overheard in code review: "Nit: I would have done this completely differently."',
  'Overheard in #general: "Who broke the build?" Narrator: everyone knew who.',
  'Overheard in standup: "I will finish it today." Narrator: they did not.',
  'Overheard in Slack: "Can someone mass-review my PR? It is small." The PR was 47 files.',
  'Overheard in retro: "Communication could be better." — The most repeated sentence in software.',
  'Overheard in #incidents: "It is not a P1." The customer disagrees.',
  'Overheard in standup: "No blockers." They have three blockers. They just gave up.',
  'Overheard in Slack: "Let us take this offline." It was never taken offline.',
  'Overheard in code review: "Why is this file 3000 lines?" "History."',
  'Overheard in #random: "I mass-deleted my node_modules and now nothing works." Classic.',
  'Overheard in standup: "Still investigating." Translation: "I have not started."',
  'Overheard in retro: "Let us document this." The action item was never completed.',
  'Overheard in Slack: "This should be easy." Narrator: it was the hardest ticket of the sprint.',
  'Overheard in code review: "Can you add a test for this?" "No."',
  'Overheard in standup: "I mass-paired with the AI all day." The team exchanged looks.',
  'Overheard in #engineering: "We need to mass-migrate to the new framework." Collective groan.',
  'Overheard in Slack: "Reply in thread please." Nobody replied in thread.',
];

/** Roasting the worst commit messages humanity has produced. */
const COMMIT_SINS: string[] = [
  'Actual commit message: "stuff." The diff was 400 lines.',
  'Actual commit message: "fix." What did it fix? Nobody knows. Nobody will ever know.',
  'Actual commit message: "WIP." Merged to main. Still WIP. Forever WIP.',
  'Actual commit message: "asdfasdf." Reviewer approved it anyway.',
  'Actual commit message: "final fix." Followed by "final fix 2" and "final fix for real this time."',
  'Actual commit message: "idk." The diff mass-rewrote the payment system.',
  'Actual commit message: "please work." It did not.',
  'Actual commit message: "ugh." Relatable. Not informative. But relatable.',
  'Actual commit message: "." Yes. Just a period. 800 lines changed.',
  'Actual commit message: "changes." Technically accurate. Maximally useless.',
  'Actual commit message: "DO NOT REVERT." It was reverted within the hour.',
  'Actual commit message: "todo: write better commit message." That was 8 months ago.',
  'Actual commit message: "fixed the thing." Which thing? THE thing.',
  'Actual commit message: "I have no idea why this works." Merged. In production.',
  'Actual commit message: "Friday." That explains everything and nothing.',
  'Actual commit message: "test." It was not a test. It was a mass-migration.',
  'Actual commit message: "oops." The diff was a mass-revert of the last three commits.',
  'Actual commit message: "initial commit." The repo is two years old.',
  'Actual commit message: "misc." The most feared word in a git log.',
  'Actual commit message: "Untitled." Your commit is not a Google Doc.',
  'Actual commit message: "sorry." The code review was indeed that bad.',
  'Actual commit message: "lol." The production outage was not, in fact, lol.',
  'Actual commit message: "yolo." Force pushed to main. Legend.',
  'Actual commit message: "it compiles." The bar has never been lower.',
  'Actual commit message: "." "." "." Three commits. Three periods. Zero context.',
];

/** Fake profound wisdom that sounds deep but is just about code. */
const FORTUNE_COOKIE: string[] = [
  'A wise developer once said: "The bug is not in the code. The bug is in the requirements."',
  'Ancient proverb: "A clean git history hides a thousand reverts."',
  'Confucius say: "Developer who mass-deploys on Friday will work on Saturday."',
  'Wisdom: "The code you do not write has zero bugs."',
  'The old masters teach: "First, understand the problem. Then, add a dependency."',
  'Proverb: "A thousand unit tests are worth one integration test. Maybe."',
  'Ancient wisdom: "The best refactor is the one you do not do."',
  'The scrolls foretell: "He who does not read the error message is doomed to Google it."',
  'Zen of programming: "Simplicity is the ultimate sophistication. Complexity is the ultimate reality."',
  'Fortune: "Your next deploy will be successful." (Results may vary.)',
  'Proverb: "A commit message written in haste is read in confusion."',
  'The elders whisper: "Not all technical debt must be repaid. Some must simply be outlived."',
  'Ancient truth: "The developer who says it cannot be done should not interrupt the agent doing it."',
  'Wisdom: "Every mass-deleted file was once someone\'s pride."',
  'Fortune: "You will mass-encounter a production bug at the worst possible time."',
  'Proverb: "The code review you skip today is the incident you debug tomorrow."',
  'The sages knew: "A function with no side effects is a function with no friends."',
  'Ancient proverb: "Give a developer a fish, they eat for a day. Teach them to mass-prompt, they never code again."',
  'Zen: "The pipeline that is always green has never been tested."',
  'Wisdom: "The fastest algorithm is the one you do not need to run."',
  'Fortune: "A mass-merge is in your future. Bring snacks."',
  'Proverb: "The developer who blames the tools is correct half the time."',
  'The ancients say: "Type safety is an illusion. A useful one. But an illusion."',
  'Fortune: "You will mass-rename a variable today. You will miss one occurrence."',
  'Wisdom: "The codebase that fears no refactor has already been abandoned."',
];

/** The absurdity of tech hiring, leetcode, and whiteboard interviews. */
const INTERVIEW_HELL: string[] = [
  'The interview asked you to reverse a binary tree. The job is CRUD forms.',
  'You mass-solved 200 LeetCode problems. The job is connecting APIs.',
  'Whiteboard interview: where you write code that will never compile on a surface that cannot run it.',
  'The interviewer asked "tell me about yourself." They meant "recite your resume but make it sound spontaneous."',
  '"Where do you see yourself in 5 years?" "Not doing whiteboard interviews." You did not get the offer.',
  'You aced the system design interview. The company has 12 users.',
  'The take-home project said "2-4 hours." It took 3 days. Nobody acknowledged this.',
  'LeetCode hard: the hazing ritual of the software industry.',
  'You mass-practiced dynamic programming. The job uses Excel.',
  'The interviewer asked you to implement a linked list. The company uses Squarespace.',
  'Five rounds of interviews. Two coding challenges. One system design. Zero feedback.',
  'The job posting says "3-5 years experience." The framework is 2 years old.',
  'They rejected you for not knowing Kubernetes. The app runs on a single EC2 instance.',
  'The coding challenge asked you to optimize for O(n log n). The production code is O(n^3) and nobody cares.',
  '"Competitive salary" means they will not tell you the salary.',
  'The interview asked about Big O notation. The biggest O at this company is the CTO saying "Oh no."',
  'You whiteboarded a perfect solution. The interviewer wanted a different perfect solution.',
  'The job says "fast-paced environment." Translation: "We do not plan."',
  'They asked you to code without an IDE, without autocomplete, and without Google. Nobody works like this.',
  'The recruiter said "culture fit." The culture is mass-deploying untested code at midnight.',
  'You spent 6 hours on their take-home. They spent 6 minutes reviewing it.',
  'The job requires 10 years of experience in a 5-year-old technology. Time travel not provided.',
  '"We are looking for a rockstar developer." The pay suggests they are looking for an intern.',
  'The interviewer mass-grilled you on algorithms. Their codebase has no algorithms. Just if-else chains.',
  'You can mass-solve any LeetCode problem. You cannot mass-solve the anxiety of waiting for the offer.',
];

const ALL_PHRASES: string[] = [
  ...SIDEKICK_ENERGY,
  ...AI_COMMENTARY,
  ...DEV_RELATABLE,
  ...DRAMATIC,
  ...PUNCHY,
  ...META_MONITORING,
  ...FOURTH_WALL,
  ...THE_ECOSYSTEM,
  ...AI_INDUSTRY,
  ...MOTIVATION,
  ...SYCOPHANCY,
  ...OBSOLESCENCE,
  ...VIBE_CODING,
  ...AFTER_HOURS,
  ...LOADING_TIPS,
  ...ERROR_MESSAGES,
  ...OVERHEARD,
  ...COMMIT_SINS,
  ...FORTUNE_COOKIE,
  ...INTERVIEW_HELL,
];

/** Pick a random phrase from all categories. */
export function getRandomPhrase(): string {
  return ALL_PHRASES[Math.floor(Math.random() * ALL_PHRASES.length)];
}

/** Random phrase wrapped in dim grey ANSI escape codes (for plain text CLI output). */
export function getRandomPhraseColored(): string {
  return `\x1b[2;90m${getRandomPhrase()}\x1b[0m`;
}

/** Random phrase wrapped in blessed `{grey-fg}` tags (for dashboard TUI). */
export function getRandomPhraseBlessedTag(): string {
  return `{grey-fg}${getRandomPhrase()}{/grey-fg}`;
}
